server:
  port: 8092

spring:

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type : com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://localhost:3306/tt?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true

  redis:
    host: localhost
    port: 6379
    max-wait: 3000        # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100       # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20          # 连接池中的最大空闲链接
    min-idle: 0           # 连接池中的最小空闲链接
    timeout: 3000         # 链接超时时间


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xwbl.xiaomingdeproject.pojo


